- name: install plugin files
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/addons/sourcemod/plugins/
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/plugins/FixHintColorMessages.smx"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/plugins/kento_mvp.smx"

- name: install scripting files
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/addons/sourcemod/scripting/
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/scripting/FixHintColorMessages.sp"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/scripting/kento_mvp.sp"

- name: install config file
  tags: custom-mvp
  get_url:
    url: "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/kento_mvp.cfg"
    dest: ~/serverfiles/csgo/addons/sourcemod/configs/

- name: install translation file
  tags: custom-mvp
  get_url:
    url: "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/translations/kento.mvp.phrases.txt"
    dest: ~/serverfiles/csgo/addons/sourcemod/translations/

- name: create directory to store mvp sound files
  file:
    path: ~/serverfiles/csgo/sound/mvp/
    state: directory

- name: copy the mp3 files
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/sound/mvp/
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/sound/mvp/illuminati.mp3"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/sound/mvp/johncena.mp3"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/sound/mvp/sirenhead.mp3"
  notify: restart_server           