- name: install plugin files
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/addons/sourcemod/plugins/
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/plugins/FixHintColorMessages.smx"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/plugins/kento_mvp.smx"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/plugins/easydownloader.smx"

- name: install scripting files
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/addons/sourcemod/scripting/
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/scripting/FixHintColorMessages.sp"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/scripting/kento_mvp.sp"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/scripting/easydownloader.sp"

- name: create directory to store easydownloader files
  file:
    path: ~/serverfiles/csgo/addons/sourcemod/configs/easydownloader/
    state: directory

- name: install easydownloader config file
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/addons/sourcemod/configs/easydownlaoder
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/easydownloader/decals.txt" 
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/easydownloader/downloadonly.txt"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/easydownloader/generics.txt"    
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/easydownloader/models.txt"    
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/easydownloader/sentencefiles.txt"       
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/easydownloader/sounds.txt"    

- name: install config file
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/addons/sourcemod/configs/
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/configs/kento_mvp.cfg"

- name: install translation file
  tags: custom-mvp
  get_url:
    url: "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/addons/sourcemod/translations/kento.mvp.phrases.txt"
    dest: ~/serverfiles/csgo/addons/sourcemod/translations/

- name: create directory to store mvp sound files
  file:
    path: ~/serverfiles/csgo/sound/mvp/
    state: directory

- name: copy the mp3 files
  tags: custom-mvp
  get_url:
    url: "{{ item }}"
    dest: ~/serverfiles/csgo/sound/mvp/
  with_items:
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/sound/mvp/illuminati.mp3"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/sound/mvp/johncena.mp3"
    - "https://cdn.jsdelivr.net/gh/anupvarghese/CSGO-MVP/sound/mvp/sirenhead.mp3"
  notify: restart_server           