#cloud-config

disable_root: true
package_update: true

packages:
  - wget
  - tar
  - ansible

write_files:
  - path: /etc/default/linuxgsm
    owner: csgoserver
    content: |
      server_name: cop_csgo
      tags: cop_csgo,executes,mirage
      gslt: ${gslt}
      rcon_passwd: ${rcon_password}
      sv_password: ${sv_password}
      cheats: 0
      map_group: de_mirage
      default_map: de_mirage
      maxplayers: 12
      tickrate: 128
      host_info: 2
      mp_roundtime: 5
      players_info: 2
      sm_executes_minplayers: 3
      sm_executes_maxplayers: 32
      sm_executes_ratio_constant: 0.475
      sm_executes_round_time: 40
      sm_executes_auto_scramble: 2
runcmd:
  - echo "localhost" > /etc/ansible/hosts | ansible-pull -U https://github.com/anupvarghese/csgo-on-cloud.git --connection=local -i 127.0.0.1 competitive.yml

