#cloud-config

disable_root: true
package_update: true

packages:
  - wget
  - tar
  - python-pip
  - python-dev

write_files:
  - path: /home/ansible-files/env.json
    owner: csgoserver
    content: |
      {
        "hostname": "${hostname}",
        "rcon_password": "${rcon_password}",
        "sv_password": "${sv_password}",
        "maxplayers": "32",
        "tickrate": "128",
        "host_info": "2",
        "gslt": "${gslt}",
        "tags": "csgo,executes,mirage",
        "mapgroup": "de_mirage",
        "defaultmap": "de_mirage"
      }

runcmd:
  - sudo pip install ansible && sudo mkdir -p /etc/ansible && sudo bash -c 'echo "localhost" > /etc/ansible/hosts'
