#cloud-config

disable_root: true
package_update: true

packages:
  - wget
  - tar
  - ansible

write_files:
  - path: /etc/default/linuxgsm
    owner: csgoserver:csgoserver
    content: |
      server_name: 128tick EXECUTES MIRAGE
      tags: 128-tick,executes,mirage
      gslt: _GSLT_
      rcon_passwd: _PASSWD_
      cheats: 0
      map_group: de_mirage
      default_map: de_mirage
      maxplayers: 12
      tickrate: 128
      host_info: 2
      players_info: 2
      sm_executes_minplayers 3
      sm_executes_maxplayers 10
      sm_executes_ratio_constant 0.475 
      sm_executes_round_time 40
      sm_executes_auto_scramble 2

runcmd:
  - su -l csgoserver -c 'ansible-pull -U https://github.com/anupvarghese/csgo-on-cloud.git --connection=local -i 127.0.0.1 competitive.yml'
