#cloud-config

disable_root: true
package_update: true

packages:
  - wget
  - tar
  - ansible

runcmd:
  - su -l csgoserver -c 'ansible-pull -U https://github.com/anupvarghese/csgo-on-cloud.git competitive.yml -i 127.0.0.1'
