# - name: read_env
#   include_vars:
#     file: /etc/default/linuxgsm
#     name: env

- name: download linuxgsm install script
  tags: download
  get_url:
    url: https://linuxgsm.sh
    dest: ~/linuxgsm.sh
    mode: "+x"

- name: install csgo gsm
  tags: download
  command: ~/linuxgsm.sh csgoserver install
  args:
    chdir: ~/
    creates: ~/csgoserver

- name: download csgo
  tags: download
  command: ~/csgoserver auto-install
  args:
    chdir: ~/
    creates: ~/serverfiles/csgo

- name: install metamod and sourcemod
  tags: basemod
  unarchive:
    src: "{{ item }}"
    remote_src: true
    dest: ~/serverfiles/csgo
  with_items:
    - "https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6460-linux.tar.gz"
    - "http://mms.alliedmods.net/mmsdrop/1.10/mmsource-1.10.7-git971-linux.tar.gz"

- name: install fix hint colour messages
  tags: plugins
  git:
    repo: https://github.com/Franc1sco/FixHintColorMessages
    dest: ~/sourcemod-plugins
    version: master

- name: install anthem
  tags: plugins
  git:
    repo: https://github.com/rogeraabbccdd/CSGO-MVP
    dest: ~/sourcemod-plugins
    version: master

- name: copy fix hint plugin to server
  copy:
    src: ~/sourcemod-plugins/FixHintColorMessages/FixHintColorMessages.smx
    dest: ~/serverfiles/csgo/addons/sourcemod/plugins

- name: copy fix hint script to server
  copy:
    src: ~/sourcemod-plugins/FixHintColorMessages/FixHintColorMessages.sp
    dest: ~/serverfiles/csgo/addons/sourcemod/scripting

- name: copy anthem plugin to server
  copy:
    src: ~/sourcemod-plugins/CSGO-MVP/addons/sourcemod/plugins/kento_mvp.smx
    dest: ~/serverfiles/csgo/addons/sourcemod/plugins

- name: copy anthem script to server
  copy:
    src: ~/sourcemod-plugins/CSGO-MVP/addons/sourcemod/scripting/kento_mvp.sp
    dest: ~/serverfiles/csgo/addons/sourcemod/plugins

- name: copy anthem translations to server
  copy:
    src: ~/sourcemod-plugins/CSGO-MVP/addons/sourcemod/translations/kento_mvp.phrases.txt
    dest: ~/serverfiles/csgo/addons/sourcemod/translations

- name: copy anthem config to server
  copy:
    src: ~/sourcemod-plugins/CSGO-MVP/addons/sourcemod/configs/kento_mvp.cfg
    dest: ~/serverfiles/csgo/addons/sourcemod/cfg

- name: copy sound
  copy:
    src: ~/sourcemod-plugins/CSGO-MVP/sound/
    dest: ~/serverfiles/csgo/sound/

- name: configure server
  tags: basemod
  template:
    src: server.cfg.j2
    dest: ~/lgsm/config-lgsm/csgoserver/csgoserver.cfg
    mode: 0644

- name: configure match
  tags: basemod
  template:
    src: game.cfg.j2
    dest: ~/serverfiles/csgo/cfg/csgoserver.cfg
    mode: 0644
  notify: restart_server

- name: "monitor job"
  tags: cron
  cron:
    user: "{{ ansible_user_id }}"
    name: "monitor"
    minute: "15"
    job: "~/csgoserver monitor"

- name: "update job"
  tags: cron
  cron:
    user: "{{ ansible_user_id }}"
    name: "update"
    minute: "30"
    job: "~/csgoserver update"

- name: "hard update job"
  tags: cron
  cron:
    user: "{{ ansible_user_id }}"
    name: "hard update"
    minute: "30"
    hour: "5"
    job: "~/csgoserver force-update"

- name: "update linuxgsm job"
  tags: cron
  cron:
    user: "{{ ansible_user_id }}"
    name: "update linuxgsm"
    minute: "0"
    hour: "2"
    weekday: "0"
    job: "~/csgoserver update-functions"

- name: "restart csgoserver"
  tags: cron
  cron:
    user: "{{ ansible_user_id }}"
    name: "restart"
    minute: "0"
    hour: "3"
    weekday: "0"
    job: "~/csgoserver restart"

- name: "start csgoserver on boot"
  tags: cron
  cron:
    user: "{{ ansible_user_id }}"
    name: "reboot"
    special_time: "reboot"
    job: "~/csgoserver start"
