--- 
- 
  become: true
  hosts: localhost
  tasks: 
    - 
      command: "dpkg --add-architecture i386"
      name: "add i386 arch"
    - 
      apt: 
        cache_valid_time: 3600
        update_cache: true
      name: "update package list"
    - 
      name: "Check if SteamCMD is installed"
      package_facts: 
        manager: apt
    - 
      name: "SteamCMD (licence agreement)"
      shell: 
        cmd: "echo steam steam/question select \"I AGREE\" | debconf-set-selections"
      when: "'steamcmd:i386' not in ansible_facts.packages"
    - 
      name: "SteamCMD (licence note)"
      shell: 
        cmd: "echo steam steam/license note '' | debconf-set-selections"
      when: "'steamcmd:i386' not in ansible_facts.packages"
    - 
      apt: 
       name: "{{ item }}"
      loop: "{{ lgsm_dependencies }}"
      name: "Install LGSM dependencies"
    - 
      group: 
        name: "{{ lgsm_group }}"
        system: true
      name: "Ensure LGSM Server Group exists"
    - 
      name: "Ensure LGSM Server user exists"
      user: 
        group: "{{ lgsm_group }}"
        name: "{{ lgsm_user }}"
        shell: /bin/bash
        system: true
    - 
      get_url: 
        dest: "/home/{{ lgsm_user }}/linuxgsm.sh"
        mode: 493
        owner: "{{ lgsm_user }}"
        url: "https://linuxgsm.sh"
      name: "Download LGSM server creator"
    - 
      name: "check if csgoserver file exists"
      register: csgoserver_file
      stat: 
        path: "/home/{{ lgsm_user }}/csgoserver"
    - 
      args: 
        chdir: "/home/{{ lgsm_user }}"
        executable: /bin/bash
      become_user: csgoserver
      name: "Initialize the csgoserver"
      register: csgoserver_init
      shell: "~/linuxgsm.sh csgoserver"
      when: "not csgoserver_file.stat.exists"
    - 
      debug: 
        var: csgoserver_init.stdout_lines
      when: "not csgoserver_file.stat.exists"
    - 
      args: 
        chdir: "/home/{{ lgsm_user }}"
        executable: /bin/bash
      become_user: csgoserver
      name: "Installing the csgoserver(this step might take 30-40min)"
      shell: "~/csgoserver auto-install > csgoinstall.log"
      when: "not csgoserver_file.stat.exists"
    - 
      copy: 
        dest: /home/csgoserver/serverfiles/csgo/cfg/csgoserver.cfg
        group: csgoserver
        owner: csgoserver
        src: files/server.cfg.j2
      name: "Copy server configuration"
      register: servercfg
    - 
      copy: 
        dest: /home/csgoserver/lgsm/config-lgsm/csgoserver/csgoserver.cfg
        group: csgoserver
        owner: csgoserver
        src: files/csgo.cfg.j2
      name: "Copy game configuration"
      register: csgocfg
    - 
      args: 
        chdir: "/home/{{ lgsm_user }}"
        executable: /bin/bash
      become_user: csgoserver
      name: "Restart the server"
      shell: "~/csgoserver restart"
      when: "servercfg.changed or csgocfg.changed"
  vars_files: 
    - ./vars/defaults.yaml
 
